Models/Roles.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace NardSmena.Models
{
    public class Roles : IdentityRole<int>
    {
        [Key]
        public int RoleId { get; set; }

        public string RoleName { get; set ;  }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using NardSmena.Models;
using System.Collections.Generic;
using System.Linq;

namespace NardSmena.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);

            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();

                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = userId,
                    UserName = user.UserName,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };

                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                IdentityResult addRoleResult = await _userManager.AddToRolesAsync(user, addedRoles);
                IdentityResult removeRoleResult = await _userManager.RemoveFromRolesAsync(user, removedRoles);

                if (addRoleResult.Succeeded && removeRoleResult.Succeeded)
                {
                    return RedirectToAction("UserList");
                }
                else
                {
                    foreach (var error in addRoleResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    foreach (var error in removeRoleResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return NotFound();
        }
    }
}

Views/Roles/Create.cshtml
@{
	ViewData["Tittle"] = "Создание роли";
}
@model string

<style>
	header {
		display: none !important;
	}

    footer {
        display: none !important;
    }

    .focus-ring:focus {
        box-shadow: 0 0 0 0.2rem rgba(255, 0, 0, 0.35);
        border-color: lightcoral;
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Добавление новой роли</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Главная</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Roles">Roles</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create" method="post">
                <div class="form-group mb-2">
                    <label for="name" class="control-label">Новая роль</label>
                    <input id="name" name="name" class="form-control focus-ring" required />
                    <span oninvalid="name" class="text-danger"></span>
                </div>

                <div class="form-group mt-3">
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-outline-success me-3"><i class="bi bi-key-fill"></i> Создать</button>
                            <a asp-action="Index" class="btn btn-outline-danger"><i class="bi bi-x-circle-fill"></i> Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Roles/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@{
	ViewData["Title"] = "Редактирование роли пользователю";
}
@model NardSmena.Models.ChangeRoleViewModel

<style>
	header {
		display: none !important;
	}

    footer {
        display: none !important;
    }

    .form-group {
        font-size: 1.5em;
    }

    input[type="checkbox"]:checked {
        background-color: red !important;
        border: none;
        box-shadow: none;
    }

    input[type="checkbox"]:focus {
        box-shadow: none;
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Изменение роли для @Model.UserName</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Главная</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Roles">Roles</a></li>
            <li class="breadcrumb-item"><a asp-action="UserList" asp-controller="Roles">UserList</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-6">
            <form asp-action="Edit" method="post">
                <input type="hidden" name="userId" value="@Model.UserId" />
                <div class="form-group mt-2">
                    <label asp-for="UserRoles" class="control-label">Роли</label>

                    <div class="row">
                        @foreach (IdentityRole role in Model.AllRoles)
                        {
                            <div class="col-md-4">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" name="roles" value="@role.Name"
                                    @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />@role.Name <br />
                                </div>
                            </div>
                        }
                    </div>
                </div>

                <div class="form-group mt-3">
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-outline-success me-3"><i class="bi bi-save-fill"></i> Сохранить</button>
                            <a asp-action="UserList" class="btn btn-outline-danger"><i class="bi bi-x-circle-fill"></i> Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
	ViewData["Title"] = "Управление ролями";
}

<style>
    header {
        display: none !important;
    }

    footer {
        display: none !important;
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Список ролей</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Главная</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Roles</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-12 text-center">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Название роли</th>
                        <th>Действие</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var role in Model)
                    {
                        <tr>
                            <td>@role.Name</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Действия">
                                    <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                                        <button type="submit" class="btn  btn-danger "><i class="bi bi-archive-fill"></i> Удалить</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <a class="btn btn-success" href="@Url.Action("Create")"><i class="bi bi-key-fill"></i> Добавить новую роль</a>
            <a class="btn btn-primary" href="@Url.Action("UserList")"><i class="bi bi-person-fill"></i> Список пользователей</a>
        </div>
    </div>
</div>

Views/Roles/UserList.cshtml
@{
	ViewData["Title"] = "Список пользователей";
}
@model IEnumerable<NardSmena.Models.User>

<style>
	header {
		display: none !important;
	}

    footer {
        display: none !important;
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Список пользователей</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Главная</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">Dashboard</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Roles">Roles</a></li>
        <li class="breadcrumb-item active">UserList</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-12 text-center">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Логин</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.FIO</td>
                        <td>@user.UserName</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Действие">
                                <a class="btn btn-primary" asp-action="Edit" asp-route-userid="@user.Id"><i class="bi bi-pencil-fill"></i> Права доступа</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
</div>