Models/RoleAssignmentViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NardSmena.Models
{
    public class RoleAssignmentViewModel
    {
        [Key]
        public int RoleAssignmentId { get; set; }
        [ForeignKey("Id")]
        public string UserId { get; set; }
        public string SelectedRole { get; set; }
        public string FIO { get; set; }
        public string Department { get; set; }
    }
}

Controllers/RoleAssignmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NardSmena.Models;
using System.Security.Claims;

namespace NardSmena.Controllers
{
	public class RoleAssignmentController : Controller
	{
		private readonly ApplicationContext _context;
		private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleAssignmentController(ApplicationContext context, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
		{
			_context = context;
			_userManager = userManager;
            _roleManager = roleManager;
		}

		[Authorize(Roles = "admin")]
		[HttpGet]
		public IActionResult Index()
		{
			var roleAssignments = _context.RoleAssignments.ToList();
            int rowCount = _context.RoleAssignments.Count();

			var roleAssignmentsViewModels = roleAssignments.Select(ra => new RoleAssignmentViewModel
			{
				RoleAssignmentId = ra.RoleAssignmentId,
				FIO = ra.FIO,
				Department = ra.Department,
				SelectedRole = ra.SelectedRole
			}).ToList();

            ViewBag.RowCount = rowCount;

			return View(roleAssignmentsViewModels);
		}

        [HttpPost]
        public async Task<IActionResult> SendRoleAssignment(string selectedRole)
        {
            if (ModelState.IsValid)
            {
                string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var user = await _userManager.FindByIdAsync(userId);

                if (user != null)
                {
                    string fio = user.FIO;
                    string department = user.Department;

                    var roleAssignment = new RoleAssignmentViewModel
                    {
                        UserId = userId,
                        FIO = fio,
                        Department = department,
                        SelectedRole = selectedRole

                    };

                    _context.RoleAssignments.Add(roleAssignment);

                    await _context.SaveChangesAsync();

                    TempData["SuccessMessagePost"] = "Ваша заявка на назначение роли успешно отправлена";

                    return Json(new { success = true});
                }
                else
                {
                    TempData["ErrorMessage"] = "Пользователь не найден";
                    return NotFound();
                }
            }

            return BadRequest(ModelState);
        }

        public async Task<IActionResult> GetRowCount()
        {
            try
            {
                int rowCount = await _context.RoleAssignments.CountAsync();

                return Json(rowCount);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Произошла ошибка при получении количества записей: {ex.Message}");
            }
        }

		[HttpPost]
		public async Task<IActionResult> ApproveRole(int roleAssignmentId, string roleName)
		{
			try
			{
				var roleAssignment = await _context.RoleAssignments.FindAsync(roleAssignmentId);
				if (roleAssignment == null)
				{
					return NotFound("Заявка не найдена");
				}

				var userId = roleAssignment.UserId;

				var user = await _userManager.FindByIdAsync(userId);
				if (user == null)
				{
					return NotFound(new { errorMessage = "Пользователь не найден" });
				}

				if (!await _roleManager.RoleExistsAsync(roleName))
				{
					return Json(new { errorMessage = "Текущая роль не найдена в базе данных, отклоните заявку" });
				}

				if (await _userManager.IsInRoleAsync(user, roleName))
				{
					return BadRequest(new { errorMessage = "Пользователь уже имеет данную роль" });
				}

				_context.RoleAssignments.Remove(roleAssignment);
				await _context.SaveChangesAsync();

				var result = await _userManager.AddToRoleAsync(user, roleName);
				if (result.Succeeded)
				{
					return Json(new { success = $"Роль {roleName} успешно назначена пользователю {user.UserName}" });
				}
				else
				{
					return BadRequest(result.Errors);
				}
			}
			catch (Exception ex)
			{
				return StatusCode(500, $"Произошла ошибка при назначении роли: {ex.Message}");
			}
		}

		[HttpPost]
		public async Task<IActionResult> RejectRole(int roleAssignmentId)
		{
			try
			{
				var roleAssignment = await _context.RoleAssignments.FindAsync(roleAssignmentId);

				if (roleAssignment == null)
				{
					return Json(new { errorMessage = "Заявка не найдена" });
				}

				_context.RoleAssignments.Remove(roleAssignment);
				await _context.SaveChangesAsync();

				return Ok("Вы успешно отклонили заявку");
			}
			catch (Exception ex)
			{
				return StatusCode(500, $"Произошла ошибка при отклонении заявки: {ex.Message}");
			}
		}
	}
}

Views/RoleAssignment/Index.cshtml
@{
	ViewData["Title"] = "Назначение ролей";
}

<style>
	header {
		display: none !important;
	}

	.btn {
		outline:none !important;
		box-shadow: none !important;
	}

	footer {
		display: none !important;
	}
</style>

@model List<RoleAssignmentViewModel>

<div class="container mt-5">
	<h2 class="mb-4">Назначение роли пользователям</h2>
	<nav aria-label="breadcumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
			<li class="breadcrumb-item"><a asp-controller="User" asp-action="Index">Dashboard</a></li>
			<li class="breadcrumb-item active" aria-current="page">RoleAssignment</li>
		</ol>
	</nav>

	<div class="container">
		<table class="table text-center">
			<caption class="caption-top">Данная страница служит платформой для приема заявлений о назначении роли, выбранным пользователем в процессе заполнения формы</caption>
			<thead>
				<tr>
					<th>#</th>
					<th>ФИО</th>
					<th>Отдел</th>
					<th>Роль</th>
					<th>Действия</th>
				</tr>
			</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr class="tr-info">
							<td>@item.RoleAssignmentId</td>
							<td>@item.FIO</td>
							<td>@item.Department</td>
							<td>@item.SelectedRole</td>
							<td class="w-25">
								<div class="row gy-3">
								<form method="post" id="approveForm_@item.RoleAssignmentId" asp-controller="RoleAssignment" asp-action="ApproveRole">
										<div class="col d-flex align-items-center justify-content-center">
											<button type="submit" class="btn btn-outline-success" data-role-assignment-id="@item.RoleAssignmentId" data-role="@item.SelectedRole"><i class="bi bi-check-lg"></i></button>
										</div>
									</form>

									<form method="post" id="rejectForm_@item.RoleAssignmentId" asp-controller="RoleAssignment" asp-action="RejectRole">
										<div class="col d-flex align-items-center justify-content-center">
											<button type="submit" id="rejectButton_@item.RoleAssignmentId" class="btn btn-outline-danger" data-role-assignment-id="@item.RoleAssignmentId"><i class="bi bi-x-lg"></i></button>
										</div>
									</form>
								</div>
							</td>
						</tr>
					}
				</tbody>
		</table>
	</div>
</div>

	<div id="alert-response" class="alert alert-success alert-dismissible position-fixed mb-custom bottom-0 end-0 m-2 rounded-3" role="alert" style="margin-bottom:7rem !important; z-index: 9999; display: none">
		<i class="bi bi-check-circle-fill"></i>
	</div>


<script src="~/js/Admin/indexPost.js"></script>